export default {


  NEW_SIGNUP_REQUEST: "NEW_SIGNUP_REQUEST",
  NEW_SIGNUP_SUCCESS: "NEW_SIGNUP_SUCCESS",
  NEW_SIGNUP_FAILURE: "NEW_SIGNUP_FAILURE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  EXCERSICE_LISTING_REQUEST: "EXCERSICE_LISTING_REQUEST",
  EXCERSICE_LISTING_SUCCESS: "EXCERSICE_LISTING_SUCCESS",
  EXCERSICE_LISTING_FAILURE: "EXCERSICE_LISTING_FAILURE",

  USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST",
  USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
  USER_DETAILS_FAILURE: "USER_DETAILS_FAILURE",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",

  EXCERSICE_LISTING_REQUEST: "EXCERSICE_LISTING_REQUEST",
  EXCERSICE_LISTING_SUCCESS: "EXCERSICE_LISTING_SUCCESS",
  EXCERSICE_LISTING_FAILURE: "EXCERSICE_LISTING_FAILURE",

  ADD_PUNCH_DATA_REQUEST: "ADD_PUNCH_DATA_REQUEST",
  ADD_PUNCH_DATA_SUCCESS: "ADD_PUNCH_DATA_SUCCESS",
  ADD_PUNCH_DATA_FAILURE: "ADD_PUNCH_DATA_FAILURE",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",

}
